### ISSUE TITLE
[ATAG industry-specific briefs] not Publishing - EPUB tools

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-atag#28]
From Tzviya, shared with permission:

> shawn: We are considering a separate one for EPUB authoring tools.
> Tzviya: there are not a lot of those, sadly
> shawn: is your feeling that EPUB authoring tools are aware of accessibility and ATAG? Or, it would be good to raise awareness?
> Tzviya: there are almost no EPUB authoring tools. There are exports from indesign, word, google docs
> Tzviya: if there were more epub tools, we would be in a much better place with accessibility

@daniel-montalvo Based on above, I think take Publishing/EPUB tools off the list of potential ATAG Briefs (then close this issue -- I just put it here for the record :-)

**Comment by daniel-montalvo** [comment]
Hi @shawna-slh 

Thanks for sharing feedback from Tzviya

Updated [requirements analysis](https://github.com/w3c/wai-intro-atag/wiki/atag-briefs-requirements-analysis)
