### ISSUE TITLE
[education] Just a couple of small edits

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-intro-atag#30]
The personas are looking great. 
For the Zola one, two suggestions: 

I can't preview uploaded content using my screen reader. 
Suggest:
I can't preview uploaded content for my students using my screen reader. 

And 
Users who have auditory, cognitive, neurological, physical, speech, and visual disabilities need to be able to preview the course content.
Suggest: 
Users who have auditory, cognitive, neurological, physical, speech, and visual disabilities need to be able to preview the course content before posting it for students. 

I know that makes them slightly longer, but I think it highlights the fact she's an educator more effectively. 

Also, in the final section, before the bulletpoints: 

ATAG covers the example personas above
Suggest: 
ATAG covers the examples from the personas above:

**Comment by daniel-montalvo** [comment]
Thanks much @jade-mc 

See [updated preview](https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/education/) and some comments below.

> I can't preview uploaded content using my screen reader. Suggest: I can't preview uploaded content for my students using my screen reader.

Done.

> And Users who have auditory, cognitive, neurological, physical, speech, and visual disabilities need to be able to preview the course content. Suggest: Users who have auditory, cognitive, neurological, physical, speech, and visual disabilities need to be able to preview the course content before posting it for students.

Done. I think these two-three extra words are of value here.

> Also, in the final section, before the bulletpoints:
> 
> ATAG covers the example personas above Suggest: ATAG covers the examples from the personas above:

We have now:

> ATAG covers the example scenarios above

I think that's more aligned with the related heading  that is also now called "Example scenarios".

Closing, feel free to reopen if that "example scenarios" phrase doesn't work.
