### ISSUE TITLE
Social media persona (brainstorming)

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-intro-atag#31]
This is massively brainstorming, it might be nonsense. 

Suggestions for the second persona: 

Everyone can Process Content at Their Own Pace

Persona: Nushi is a blind disability influencer with a large following. She uses a screen reader that reads aloud the information on her screen. 

    Problem:  I can't search through the comments on my posts or skip to new comments easily.

    Works well:  I can search through comments quickly using my screen reader so I can react and reply to followers easily. 

People who interact with social platforms have different abilities. Some need to read and access content at a different pace. Your tool should allow them to decide how they want to process the new content that appears.

**Comment by daniel-montalvo** [comment]
Thanks @jade-mc 

Someone who can easily read comments and move from comment to comment seems like a much stronger case. I will update the page accordingly.

**Comment by daniel-montalvo** [comment]
Hi @jade-mc 

We did update these two yesterday based on more input we received.

Please see:

- [No-code](https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/no-code/)
- [Social Media](https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/social-media/)

We changed the second persona in social to someone woh actually has a reading disability, which was suggested to fit more with the "reading at their own pace" use case.

Could you have a look and raise any other big issues you encounter this morning for us to discuss in eo-plan this afternoon?

**Comment by daniel-montalvo** [comment]
Closing as per updates in #34
