### ISSUE TITLE
[all] [medium-low] minimal header, Page Contents on right

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-atag#33]
use new design, e.g., https://www.w3.org/WAI/WCAG2/supplemental/patterns/o5p03-manageable-quantity/

Priority? I think:
* [low] for MVP in December
* [medium] for soonish

and, I'm hoping that in early December, I can use @SteveALee 's documentation to know how to do it :-)

**Comment by SteveALee** [comment]
Documentation updated  https://wai-website-theme.netlify.app/writing/standalone-resources/
