### ISSUE TITLE
ATAG briefs, LMS,no-code,social-media -- 

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-intro-atag#41]
I will try to think of wording - but I feel like the LMS intro of Why Accessibility Matters needs to be stronger in terms of providing access to educational materials for all people.  I know LMS covers many industries besides traditional K-12 or colleges or universities, but regardless of where or why they are using this, they come to an LMS to learn something, and if the content is inaccessible or the interface is inaccessible, you are keeping someone from learning AND/OR from teaching someone what they know.  

Was this discussed?  Apologies if it was discussed during a meeting that I missed.

**Comment by daniel-montalvo** [comment]
Thanks @kakinney 

We are currently discussing updates to the intro paragraphs that are aligned with your suggestions. For some examples, see #40 

I will update later today.

**Comment by kakinney** [comment]
Thank you @daniel-montalvo!!

**Comment by daniel-montalvo** [comment]
Thanks @kakinney 

To reinforce the idea of "providing access to educational materials for all people", we have now added:

> Accessibility for instructors and students is an essential aspect of diversity, equity, and inclusion.


https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/education/#why-accessibility-matters

Cclosing now. Feel free to reopen if you think this is not completely addressed.
