### ISSUE TITLE
[High, easy] ATAG briefs [all] update footers

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-atag#45]
let me know if you have questions...

**Comment by daniel-montalvo** [comment]
Footers updated.

https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/education/#wai-site-footer

https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/no-code/#wai-site-footer

https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/social-media/#wai-site-footer

Please take a look, you may have further suggestions. 

In the meantime, putting this as "[High] Tweaks to footers" for me to be able to do better filtering of issues :-)

**Comment by shawna-slh** [comment]
Thanks @daniel-montalvo 

minor:
* [ ] extra space and period at the end of "First published December 2022. ."
* [ ] no comma needed before 'and' if there's only 1 name: "Contributors: Kevin White, and [participants of the Education and Outreach Working Group](https://www.w3.org/groups/wg/eowg/participants)."
* [ ] _pending input_ -- use the simpler funder ack from the [template](https://raw.githubusercontent.com/w3c/wai-resource-template/main/content/index.md): "Developed as part of the WAI-Guide project, co-funded by the European Commission."?

_(I'll send separate message about names.)_
