### ISSUE TITLE
[med] ATAG briefs [all] scenario-persona-problem-works-well format

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-intro-atag#46]
We at EOWG are familiar with the format that goes: 
Problem: blah blah
Works well: blah blah 
But the rest of the world may not be. I am afraid that in trying to be succinct we plop people down into the middle of a scenario that is not explained and could be quite confusing. 

Suggested type of change:
Scenario:  Irina is the director of an online professional training center. She is an expert in her job; however, she doesn't know much about accessibility.  She has students with disabilities and needs an LMS that produces accessible content. The instructor has some responsibility. However, a proper tool will provide prompts and information to help instructors know what to do to provide accessible course content.

    Problem: "I'm adding charts to our courses. I have no idea what I need to do to make them accessible to students with disabilities and the tool does not suggest that support."

    Works well: " I found an LMS that prompts me to add a short description and a full text alternative for the chart data whenever I add a chart to the lesson. There's also "Learn More" that explains why it's important for accessibility, and how to do it well. "

**Comment by shawna-slh** [comment]
> We at EOWG are familiar with the format that goes:
> Problem: blah blah
> Works well: blah blah

We first did these in [What’s New in WCAG 2.1](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/) with very little introduction or explanation &mdash; only in the summary: "It includes quotes from personas (fictional people) to help you understand some aspects of the success criteria.". People love 'em, and I haven't heard of confusion. (I do know that doesn't mean there isn't any.)

I've even seen others copying that format in their documents.

I checked with a few folks without usability background about understandability of "persona", and have gotten feedback that it makes sense.

For these ATAG briefs examples, we used the approach of **succinctly** guiding the reader to:
1. relate to the persona as a user of their tool
2. feel the pain of the problem in a tool
3. realize there's a better way to make the tool accessible
4. introduce the broader issue -- which when then tie to ATAG in the last section

I'm wondering if by moving #4 to #1, we'd decrease the skim-ability and decrease the impact?

I also wonder if more in the section intro sentence could help? Maybe along the lines of: @@

Would be good to get more input from other in EO, too. :-)

**Comment by daniel-montalvo** [comment]
Hi @sharronrush  @shawna-slh 

Thanks much for your input

For all three briefs, I propose:

- We change intro sentence to:
  > These persona scenarios are examples of accessibility issues that disabled people experience using LMS | no-code | social media tools. "Problem" shows user experiences with tools that have accessibility issues. "Works well" shows experiences with accessible tools.

- WE come back to this after we publish this first iteration for further refinement.

Are we all OK with that approach??

**Comment by sharronrush** [comment]
Sure I am fine with that approach. Thanks Daniel

**Comment by shawna-slh** [comment]
> These persona scenarios are examples of accessibility issues that disabled people experience using no-code tools. “Problem” shows user experiences with tools that have accessibility issues. “Works well” shows experiences with accessible tools.

How about this to be more succinct and remove redundancies:
> These _persona_ scenarios show examples of accessibility _problems_ that disabled people experience using no-code tools, and what _works well_ in tools that are accessible.

note that the words _persona_, _problem_, _works well_ -- are italic in the examples, so probably good to have them italic in the intro sentence.

**Comment by shawna-slh** [comment]
+1 for publishing first iteration in Dec with additional clarification *and* leaving the issue open to address with EOWG in early 2023

Consider revising order as Sharron proposes.

Consider maybe put the explanation first, before the scenario:
1. introduce the broad issue
2. persona scenario
3. problem
4. works well

**Comment by daniel-montalvo** [comment]
Done.
