### ISSUE TITLE
[high] ATAG briefs [LMS] quadriplegic wording

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-intro-atag#47]
Do we want to say of Aroon that "He is a quadriplegic and uses ..." or might we want to say instead something like: "Due to his quadriplegia he uses...."

**Comment by shawna-slh** [comment]
[current wording in context](https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/education/#everyone-can-edit-content)

+1 to a wording change

Maybe even more clear than "quadriplegia", e.g.:
> He can't move his arms due to a spinal cord injury and he uses speech recognition to navigate through applications and websites.

**Comment by iadawn** [comment]
+1 to @shawna-slh suggested change

**Comment by daniel-montalvo** [comment]
thanks @sharronrush and @shawna-slh for your input.

Added in
https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/education/


Closing, feel free to reopen if neded.
