### ISSUE TITLE
[Low] Use of 'persona'

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-intro-atag#50]
While _persona_ is largely correct, I think its use could be avoided to simplify things.

For example:

> These _persona_ scenarios show examples of accessibility ...

Could be:

> These short scenarios show examples of accessibility ...

And,

> _Person_: ...

Could change to:

> _Scenario_: ...

**Comment by shawna-slh** [comment]
hum, I think "persona" is a positive word for those who know what they are, and not confusing for those who don't. (I've checked with just a couple people about that.)

**Comment by daniel-montalvo** [comment]
Hello @iadawn 

I agree with @shawn on this one. I think "persona" is sufficiently understood in this context. The explanatory sentence we have now added helps reinforce its meaning.

I think we should leave this open and come back to it after we publish the first iteration.

**Comment by daniel-montalvo** [comment]
Closing. We have related open issues for further refinement that will possibly take care of this.

https://github.com/w3c/wai-intro-atag/milestone/2
