### ISSUE TITLE
Minor grammatical error on Social Media brief

### ISSUE THREAD

**Issue by stringyland** [w3c/wai-intro-atag#53]
The third persona item on the [Social Media Guidelines](https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/social-media/) has a heading of "The tool **help** create accessible multimedia", which should probably be "The tool **helps** create accessible multimedia". 

This would also match the other briefs which have "The LMS helps make course content accessible" and "The tool helps make images and videos accessible" for their third items.

I'm sure everyone will know what it means, but I thought I'd just mention it.

**Comment by daniel-montalvo** [comment]
Thanks @stringyland 

Closing. This is now fixed.
https://atag-briefs--wai-intro-atag.netlify.app/standards-guidelines/atag/social-media/
